env: ${ENV:dev}

server:
  port: 15014
  servlet:
    context-path: /auth-service
  # error handle default config
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

# actuator metrics
management.endpoint.metrics.enabled: true
management.endpoints.web.exposure.include: '*'
management.endpoint.prometheus.enabled: true
management.endpoints.enabled-by-default: false
management.endpoint.info.enabled: true
management.endpoint.health.enabled: true
management.endpoint.shutdown.enabled: true

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
spring:
  application:
    name: auth-service
  jackson:
    property-naming-strategy: SNAKE_CASE # since jackson 2.7
    time-zone: Asia/Ho_Chi_Minh

  # JPA / HIBERNATE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: false
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  task:
    scheduling:
      pool:
        size: 10

mysql:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://127.0.0.1:3306/auth_service?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh&useLegacyDatetimeCode=false}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}

jwt.expiration: 3600000
jwt.secret-key: b1d782d0983b3043d4fb16420af6dcc6aa9bf1747b99568eb4ef50c8cdc55b41aa8c53aebc736c09a53ce21b28ce00ca4a560c56aa94d7a30d94fdad5c2d6202c8a40decd7377faf6553e82ff843283c