apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-broker
  labels:
    name: kafka-broker
spec:
  storageClassName: gms-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/gms/kafka/configs
    server: 172.16.10.1
