apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-broker
  namespace: gms
  labels:
    name: kafka-broker
spec:
  storageClassName: mystorageclass
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/gms/kafka/configs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gms
  name: kafka-broker
spec:
  storageClassName: mystorageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
