apiVersion: v1
kind: ConfigMap
metadata:
  namespace: gms
  name: kafka-sasl-config
data:
  kafka_server_jaas.conf: |
    KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
        username="admin"
        password="admin-secret"
        user_admin="admin-secret";
    }; 

