apiVersion: v1
kind: Service
metadata:
  namespace: gms
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
    - name: web
      port: 15672
      targetPort: 15672
    - name: internal
      port: 5672
      targetPort: 5672
  type: ClusterIP
  selector:
    app: rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gms
  name: rabbitmq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq-gms
          image: rabbitmq:3.9-management
          ports:
            - name: web
              containerPort: 15672
            - name: internal
              containerPort: 5672

          env:
            - name: RABBITMQ_DEFAULT_USER
              value: admin
            - name: RABBITMQ_DEFAULT_PASS
              value: admin123
          resources:
            limits:
              cpu: 150m
              memory: 150Mi
