apiVersion: v1
kind: Service
metadata:
  namespace: gms
  name: redis
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30677
  type: NodePort
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gms
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis-gms
          image: redis:latest
          ports:
            - containerPort: 6379
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli ping
            initialDelaySeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 150m
              memory: 150Mi
