apiVersion: v1
kind: Service
metadata:
  namespace: gms
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
      targetPort: 2181
  type: ClusterIP
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gms
  name: zookeeper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper-gms
          image: confluentinc/cp-zookeeper:latest
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: '2181'
            - name: ZOOKEEPER_TICK_TIME
              value: '2000'
          # resources:
          #   limits:
          #     cpu: 150m
          #     memory: 150Mi
