apiVersion: v1
kind: Service
metadata:
  namespace: gms
  name: frontend-cd
  labels:
    app: frontend-cd
spec:
  ports:
    - port: 7776
      targetPort: 7777
      nodePort: 31077
    - port: 444
      targetPort: 443
      nodePort: 31443
  type: NodePort
  selector:
    app: frontend-cd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gms
  name: frontend-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-cd
  template:
    metadata:
      labels:
        app: frontend-cd
    spec:
      containers:
        - name: frontend
          image: ftvdexcz/gms-frontend-ci:36
          ports:
            - containerPort: 7777
            - containerPort: 443
          envFrom:
            - configMapRef:
                name: frontend
          # resources:
          #   limits:
          #     cpu: 250m
          #     memory: 250Mi
