apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '5'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"chatops-service","argocd.argoproj.io/instance":"backend-chatops-service"},"name":"chatops-service","namespace":"idg-backend-dev"},"spec":{"replicas":1,"revisionHistoryLimit":1,"selector":{"matchLabels":{"app":"chatops-service"}},"template":{"metadata":{"labels":{"app":"chatops-service","monitor":"prometheus"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"chatops-service"}}],"image":"idg-repository-prod.vnpt.vn/devops/chatops-service:11","imagePullPolicy":"IfNotPresent","name":"chatops-service","ports":[{"containerPort":15052,"name":"app"},{"containerPort":7799,"name":"idg-metric"}],"resources":{"limits":{"cpu":"500m","memory":"1024Mi"},"requests":{"cpu":"250m","memory":"256Mi"}},"volumeMounts":[{"mountPath":"/logs/","name":"applog"},{"mountPath":"/etc/localtime","name":"tz-config"}]}],"volumes":[{"emptyDir":{},"name":"applog"},{"configMap":{"name":"fluentdconf"},"name":"fdconf"},{"hostPath":{"path":"/usr/share/zoneinfo/Asia/Ho_Chi_Minh","type":"File"},"name":"tz-config"}]}}}}
  creationTimestamp: '2023-12-18T03:02:58Z'
  generation: 5
  labels:
    app: chatops-service
    argocd.argoproj.io/instance: backend-chatops-service
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:template:
            f:spec:
              f:hostAliases:
                .: {}
                k:{"ip":"149.154.167.220"}:
                  .: {}
                  f:hostnames: {}
                  f:ip: {}
      manager: rancher
      operation: Update
      time: '2023-12-18T04:11:36Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:app: {}
            f:argocd.argoproj.io/instance: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
                f:monitor: {}
            f:spec:
              f:containers:
                k:{"name":"chatops-service"}:
                  .: {}
                  f:envFrom: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":7799,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:name: {}
                      f:protocol: {}
                    k:{"containerPort":15052,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:name: {}
                      f:protocol: {}
                  f:resources:
                    .: {}
                    f:limits:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                    f:requests:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/etc/localtime"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                    k:{"mountPath":"/logs/"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
              f:volumes:
                .: {}
                k:{"name":"applog"}:
                  .: {}
                  f:emptyDir: {}
                  f:name: {}
                k:{"name":"fdconf"}:
                  .: {}
                  f:configMap:
                    .: {}
                    f:defaultMode: {}
                    f:name: {}
                  f:name: {}
                k:{"name":"tz-config"}:
                  .: {}
                  f:hostPath:
                    .: {}
                    f:path: {}
                    f:type: {}
                  f:name: {}
      manager: argocd-controller
      operation: Update
      time: '2023-12-19T02:50:16Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2023-12-19T02:50:20Z'
  name: chatops-service
  namespace: idg-backend-dev
  resourceVersion: '384566982'
  uid: f71adec0-866c-416d-bf31-c79e4ddc73a8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: chatops-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: chatops-service
        monitor: prometheus
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: chatops-service
          image: idg-repository-prod.vnpt.vn/devops/chatops-service:11
          imagePullPolicy: IfNotPresent
          name: chatops-service
          ports:
            - containerPort: 15052
              name: app
              protocol: TCP
            - containerPort: 7799
              name: idg-metric
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /logs/
              name: applog
            - mountPath: /etc/localtime
              name: tz-config
      dnsPolicy: ClusterFirst
      hostAliases:
        - hostnames:
            - api.telegram.org
          ip: 149.154.167.220
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: applog
        - configMap:
            defaultMode: 420
            name: fluentdconf
          name: fdconf
        - hostPath:
            path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
            type: File
          name: tz-config
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2023-12-18T07:25:46Z'
      lastUpdateTime: '2023-12-18T07:25:46Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2023-12-18T03:02:58Z'
      lastUpdateTime: '2023-12-19T02:50:20Z'
      message: ReplicaSet "chatops-service-57f856bc5b" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
