apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: local.csi.openebs.io
    volume.kubernetes.io/provisioner-deletion-secret-name: ''
    volume.kubernetes.io/provisioner-deletion-secret-namespace: ''
  creationTimestamp: '2023-12-20T10:34:39Z'
  finalizers:
    - kubernetes.io/pv-protection
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:pv.kubernetes.io/provisioned-by: {}
            f:volume.kubernetes.io/provisioner-deletion-secret-name: {}
            f:volume.kubernetes.io/provisioner-deletion-secret-namespace: {}
        f:spec:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:claimRef:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:namespace: {}
            f:resourceVersion: {}
            f:uid: {}
          f:csi:
            .: {}
            f:driver: {}
            f:fsType: {}
            f:volumeAttributes:
              .: {}
              f:openebs.io/cas-type: {}
              f:openebs.io/volgroup: {}
              f:storage.kubernetes.io/csiProvisionerIdentity: {}
            f:volumeHandle: {}
          f:nodeAffinity:
            .: {}
            f:required: {}
          f:persistentVolumeReclaimPolicy: {}
          f:storageClassName: {}
          f:volumeMode: {}
      manager: csi-provisioner
      operation: Update
      time: '2023-12-20T10:34:39Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2023-12-20T10:34:39Z'
  name: pvc-53eea696-3984-4bdd-b299-4d962dd9c518
  resourceVersion: '388051621'
  uid: 52327468-4d77-41a9-96e5-11898dab03e6
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: redis-data-redis-3
    namespace: may
    resourceVersion: '388051532'
    uid: 53eea696-3984-4bdd-b299-4d962dd9c518
  csi:
    driver: local.csi.openebs.io
    fsType: xfs
    volumeAttributes:
      openebs.io/cas-type: localpv-lvm
      openebs.io/volgroup: idg
      storage.kubernetes.io/csiProvisionerIdentity: 1692845139860-8892-local.csi.openebs.io
    volumeHandle: pvc-53eea696-3984-4bdd-b299-4d962dd9c518
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: openebs.io/nodename
              operator: In
              values:
                - worker-02
  persistentVolumeReclaimPolicy: Delete
  storageClassName: lvm-thick
  volumeMode: Filesystem
status:
  phase: Bound
