apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: 172.16.10.1
            - name: NFS_PATH
              value: /gms-data-nfs
      volumes:
        - name: nfs-client-root
          nfs:
            server: 172.16.10.1
            path: /gms-data-nfs
