apiVersion: v1
kind: Service
metadata:
  namespace: gms
  name: gms-mysql
  labels:
    app: mysql
spec:
  ports:
    - name: mysql-port
      port: 3306
      targetPort: 3306
      nodePort: 32307
  selector:
    app: mysql
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gms
  name: gms-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: mysql
      containers:
        - name: gms-garbage-mysql
          image: mysql:8.0.13
          ports:
            - name: http
              containerPort: 3306
          envFrom:
            - configMapRef:
                name: mysql
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
