apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
  namespace: gms
  labels:
    name: mysql
spec:
  storageClassName: mystorageclass
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/gms/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gms
  name: mysql
spec:
  storageClassName: mystorageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
