apiVersion: v1
kind: Service
metadata:
  namespace: gms
  name: gms-mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 32307
  selector:
    app: mysql
  type: NodePort

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: gms
spec:
  serviceName: gms-mysql
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-mysql
      containers:
        - name: gms-mysql
          image: mysql:8.0.13
          ports:
            - name: http
              containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        namespace: gms
        name: data-mysql
      spec:
        storageClassName: mysql
        resources:
          requests:
            storage: 150Mi
        accessModes:
          - ReadWriteOnce
